### PR TITLE
Add checkError to every _request call

### PR DESCRIPTION
**Pull request by DBX12**
Added error checking for every request as it was not used everywhere. For example not having the correct access token scope led to the error message `jq: error (at <stdin>:0): Cannot iterate over null (null)` instead of a nice explanation what went wrong.

There was already one failed test in the version at `679d5c5` with the message: 
```
✗ _request - basic parameters                                                                                         
   (in test file tests/unit.bats, line 70)
     `[[ "${capture[0]}" =~ "curl-stub -s -X GET -H Accept: application/json -H Content-Type: application/json -u dummy:super-secret-password" ]]' failed
```
~A new failure was introduced with this code change:~ _solved_

```
✗ webhook - list
   (in test file tests/unit.bats, line 228)
     `[[ "$status" = "0" ]]' failed
```

However, I'm not very good with the bats test suite, so can you check if those are legitimate errors which need fixing or errors in the test itself?

### CODE REVIEW

**Comment by DBX12** [comment]
With the quoted $response, the second error is gone, nice.
Maybe add [shellcheck](https://github.com/koalaman/shellcheck) to the codestyle step as well?

**Comment by particleflux** [comment]
Good stuff :+1: 
Was noticing missing error handling in a few cases as well.

Bump (let's see if CI is triggered)

**Review by particleflux — APPROVED** [review]

**Comment by particleflux** [comment]
Looks good, that failed check on CI is due to a missing token for coverage reporting on forked CI runs. Might fix that after merging.

**Comment by particleflux** [comment]
Indeed, tests on `master` passed, Thanks for the contribution!

**Pull request merged**
